export { Post } from "./components/Post"
export { Form } from "./components/Form"
export { PostsList } from "./components/PostsList"
export type { IPost } from "./components/Post"
export  * from "./actions/postsActions"
export  * from "./reducers/postsReducer"
