export { AuthForm } from "./AuthForm"
export { DetailsForm } from "./DetailsForm"
export * as api from "./api/requests"
export * from "./actions/authActions"
export * from "./reducers/authReducer"
export type { IFormData } from "./api/requests"
