export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const LOGOUT = "LOGOUT";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const UPLOAD_USER_PHOTO_REQUEST = "UPLOAD_USER_PHOTO_REQUEST";
export const UPLOAD_USER_PHOTO_SUCCESS = "UPLOAD_USER_PHOTO_SUCCESS";
export const UPLOAD_USER_PHOTO_ERROR = "UPLOAD_USER_PHOTO_ERROR";