export const FETCH_ALL_REQUEST = "FETCH_ALL_REQUEST";
export const FETCH_ALL_SUCCESS = "FETCH_ALL_SUCCESS";
export const FETCH_ALL_FAIL = "FETCH_ALL_FAIL";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";

export const GET_USER_PHOTOS_REQUEST = "GET_USER_PHOTOS_REQUEST";
export const GET_USER_PHOTOS_SUCCESS = "GET_USER_PHOTOS_SUCCESS";
export const GET_USER_PHOTOS_FAILURE = "GET_USER_PHOTOS_FAILURE";

export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const CLEAR_USER_POSTS = "CLEAR_USER_POSTS";

export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_FAIL = "DELETE_FAIL";